[project]
name = "iris-fastapi"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "fastapi",
    "uvicorn",
    "scikit-learn",
    "joblib",
    "numpy",
    "pydantic",
    "pytest",
    "httpx"
]

